name: trade_statistics
description: "A trade statistics application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  statistics: ^1.0.0
  dartz: ^0.10.1
  fl_chart: ^0.66.2
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  freezed_annotation: ^2.4.1
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  analyzer: ^7.1.0

flutter:
  uses-material-design: true

dependency_overrides:
  analyzer: ^5.13.0
